<?php
/**
 * RadiologyTestOrder  model
 *
 * PHP 5
 *
 * @copyright     Copyright 2011 KloudData Inc.  (http://www.klouddata.com/)
 * @link          http://www.klouddata.com/
 * @package       RadiologyParameter Model
 * @since         CakePHP(tm) v 2.0
 * @license       MIT License (http://www.opensource.org/licenses/mit-license.php)
 * @author        Pankaj wanjari
 * @functions 	 : Add test respective to patient	
 */
class RadioManager extends AppModel {
	
		public $name = 'RadioManager';
		public $useTable  = 'radiology_test_orders';
		 public $specific = true;
	  function __construct($id = false, $table = null, $ds = null) {
        $session = new cakeSession();
		$this->db_name =  $session->read('db_name');
        parent::__construct($id, $table, $ds);
    } 
	function insertTestOrder($data=array(),$action='insert'){
			$session = new cakeSession();
			//implode test ids with seperator "|"	
			//first remove all the existance instances of patient ID(trick to update the current record)
			//$this->deleteAll(array('patient_id'=> $data['RadiologyTestOrder']['patient_id'])); 
			if(is_array($data['RadiologyTestOrder']['radiology_id'])){
				foreach($data['RadiologyTestOrder']['radiology_id'] as $labID){
					
					if(empty($data['RadiologyTestOrder']['id'])){
						$orderArr['created_by'] = $session->read('userid');
						$orderArr['create_time'] = date("Y-m-d H:i:s");
					}else{
						$this->id = $data['RadiologyTestOrder']['id'] ; 
						$orderArr['modified_by'] = $session->read('userid');
						$orderArr['modify_time'] = date("Y-m-d H:i:s");
					}
				 	$orderArr['patient_id'] = $data['RadiologyTestOrder']['patient_id'];
				 	$orderArr['radiology_id'] = $labID;
				 	 
					$result =  $this->save($orderArr);
					//generate lab id for each new test ordered
				    $laboratoryToken->id ='';					 
					$radId =  $this->autoGeneratedRadID($this->id); 
					$this->save(array('order_id'=>$radId)); 
					$this->id  ='';
				}
			}else{
				return true ;
			}		  
			
			return $result ;
			
		}
		
/**
	 * Called after inserting lab data
	 *
	 * @param id:latest RadiologyTestOrder table ID
	 *  
	 * @return lab ID
	 **/
	    public function autoGeneratedRadID($id=null){
	    	//$patient_info=array('Patient'=>array('first_name'=>'Pankaj','admission_type'=>'IPD','location_id'=>1));   
	    	$Location = ClassRegistry::init('Location'); 
	    	$session = new cakeSession();
	  		$count = $this->find('count',array('conditions'=>array('RadiologyTestOrder.create_time like'=> "%".date("Y-m-d")."%")));
	  		 
	  		if($count==0){
	  			$count = "001" ;
	  		}else if($count < 10 ){
	  			$count = "00$count"  ;
	  		}else if($count >= 10 && $count <100){
	  			$count = "0$count"  ;
	  		}
	  		$month_array = array('A','B','C','D','E','F','G','H','I','J','K','L'); 			 
	  		//find the Hospital name.
	  		 
	  		$Location->unbindModel(
	        	array('belongsTo' => array('City','State','Country'))
	    	);  		 		
	 		 
	 		#$hospital = $Location->read('Facility.name,Location.name',$session->read('locationid'));
	 		
	  		//creating patient ID 
	  		$unique_id   = 'RAD';  
			$facility = $this->Session->read('facility');
			$location = $this->Session->read('location');	
	  		$unique_id  .= substr($facility,0,1); //first letter of the hospital name
	  		$unique_id  .= substr($location,0,2);//first 2 letter of d location 
	  		$unique_id  .= date('y'); //year
	  		$unique_id  .= $month_array[date('n')-1];//first letter of month 	
	  		$unique_id  .= date('d');//day
	  		$unique_id .= $count;
	  		return strtoupper($unique_id) ; 
			 
	    	
	    }
	    
	   
}