<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  
   <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>QR code List</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

 <link href="../assets/img/favicon.png" rel="icon">
  <link href="../assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="../assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="../assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="../assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="../assets/vendor/quill/quill.snow.css" rel="stylesheet">
  <link href="../assets/vendor/quill/quill.bubble.css" rel="stylesheet">
  <link href="../assets/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="../assets/vendor/simple-datatables/style.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <!--<link href="../assets/css/style.css" rel="stylesheet">-->

  <style>
    /* Optional CSS for controlling QR Code size if needed in HTML */
    .qr-code {
      width: 200px; /* Base size for the QR code */
      height: 300px;
    }
  </style>
</head>
<body> 

 <!--<main id="main" class="main">-->
    <div class="pagetitle">
      <h1>Unique QR Code List</h1>
      <nav>
    
      </nav>
    </div>
    <!-- End Page Title -->
    <section class="section">
      <div class="row">
        <div class="col-lg-12">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">QR Code</h5>
              <!-- Table with stripped rows -->
              <table class="table datatable">
                <thead>
                  <tr>
                      <th>Patient ID.</th>
                    <th>
                      <b>N</b>ame
                    </th>
                    <th>Phone</th>
                    <th>Next Of kin Number </th>
                    <th data-type="date" data-format="YYYY/DD/MM">Registartion Date</th>
                    <th>Generated By</th>
                    <th>Company/Organisation</th>
                    <th>Download</th>
                  </tr>
                </thead>
                <tbody>
                     <?php if (!empty($persons)): ?>
            <?php foreach ($persons as $person): ?>
                  <tr>
                    <td><?php echo $person['Person']['patient_uid']; ?></td>
                    <td>  <a href="https://hopesoftwares.com/Patients/new_patient_hub/<?php echo $person['Patient']['id']; ?>/<?php echo $person['Person']['id']; ?>">
                            <?php echo $person['Person']['first_name']; ?> <?php echo $person['Person']['last_name']; ?>
                        </a></td>
                    <td><?php echo $person['Person']['mobile']; ?></td>
                    <td><?php echo $person['Person']['next_of_kin_mobile']; ?></td>
                    <td><?php echo $person['Person']['create_time']; ?></td>
                    <td><?php echo $person['Person']['qr_created_by']; ?></td>
                    <td><?php echo $person['Person']['company_name']; ?></td>
                     <td>
                        <!-- Trigger the function on button click -->
                    <!--    <button class="btn btn-success" onclick="prepareAndDownloadQRCode('<?php echo $person['Person']['mobile']; ?>', '<?php echo $person['Person']['first_name'] . ' ' . $person['Person']['last_name']; ?>', '<?php echo $person['Person']['next_of_kin_mobile']; ?>')">Download QR</button>-->
                    <!--</td>-->
                    <td>
    <button class="btn btn-success" onclick="prepareAndDownloadQRCode('<?php echo $person['Person']['mobile']; ?>', '<?php echo $person['Person']['first_name'] . ' ' . $person['Person']['last_name']; ?>', '<?php echo $person['Person']['next_of_kin_mobile']; ?>')">Download QR</button>
</td>

                  </tr>
            
                  <?php endforeach; ?>
        <?php else: ?>
            <tr>
                <td colspan="6">No records found.</td>
            </tr>
        <?php endif; ?>
                </tbody>
              </table>
              <!-- End Table with stripped rows -->

            </div>
          </div>

        </div>
      </div>
    </section>

  <!--</main>-->
  <!-- End #main -->

  
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="../assets/vendor/apexcharts/apexcharts.min.js"></script>
  <script src="../assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="../assets/vendor/chart.js/chart.umd.js"></script>
  <script src="../assets/vendor/echarts/echarts.min.js"></script>
  <script src="../assets/vendor/quill/quill.js"></script>
  <script src="../assets/vendor/simple-datatables/simple-datatables.js"></script>
  <script src="../assets/vendor/tinymce/tinymce.min.js"></script>
  <script src="../assets/vendor/php-email-form/validate.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/qrcode/build/qrcode.min.js"></script>


  <!-- Template Main JS File -->
  <script src="../assets/js/main.js"></script>
<script>
function prepareAndDownloadQRCode(mobile, name, nextOfKinPhone) {
    const overlayImageUrl = 'https://hopesoftwares.com/img/qr2.png';
    const qrContentUrl = `https://admin.emergencyseva.in/public/emergency-sewa?mobile=${mobile}&next_of_kin=${nextOfKinPhone}`;

    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    const overlayImage = new Image();

    overlayImage.crossOrigin = 'anonymous';
    overlayImage.src = overlayImageUrl;

    overlayImage.onload = () => {
        canvas.width = overlayImage.width;
        canvas.height = overlayImage.height;
        ctx.drawImage(overlayImage, 0, 0);

        // Set font for text
        ctx.font = 'bold 30px Arial';
        ctx.fillStyle = 'white';
        ctx.textAlign = 'center';

        // Adjusted positions (from your old working code)
        const textX = canvas.width / 2 - 5;
        const textY = (canvas.height - 280) / 3 + 90;
        const phoneTextY = textY + 40;

        // Draw name and kin number
        ctx.fillText(name, canvas.width / 2, textY);
        ctx.fillText(nextOfKinPhone, canvas.width / 2, phoneTextY);

        // Generate QR and draw it
        QRCode.toDataURL(qrContentUrl, { width: 280, margin: 1 }, function (err, url) {
            if (err) {
                console.error(err);
                return;
            }

            const qrImage = new Image();
            qrImage.crossOrigin = 'anonymous';
            qrImage.src = url;

            qrImage.onload = () => {
                const qrCodeWidth = 280;
                const qrCodeHeight = 280;
                const qrX = (canvas.width - qrCodeWidth) / 2;
                const qrY = (canvas.height - qrCodeHeight) / 2 + 80;

                ctx.drawImage(qrImage, qrX, qrY, qrCodeWidth, qrCodeHeight);

                const finalImage = canvas.toDataURL("image/png");
                const link = document.createElement('a');
                link.download = `${name.replace(/\s+/g, '_')}_${mobile}_QR.png`;
                link.href = finalImage;
                link.click();
            };
        });
    };
}
</script>



  
// <script>
// function prepareAndDownloadQRCode(mobile, name, nextOfKinPhone) {
//     const qrCodeUrl = `https://hopesoftwares.com/uploads/qrcodes/QRCode_${mobile}.png`;
//     const overlayImageUrl = 'https://hopesoftwares.com/img/qr2.png';

//     // Create a canvas to merge the images
//     const canvas = document.createElement('canvas');
//     const ctx = canvas.getContext('2d');

//     const qrImage = new Image();
//     const overlayImage = new Image();

//     qrImage.crossOrigin = 'anonymous';
//     overlayImage.crossOrigin = 'anonymous';

//     qrImage.src = qrCodeUrl;
//     overlayImage.src = overlayImageUrl;

//     qrImage.onload = () => {
//         overlayImage.onload = () => {
//             // Set canvas dimensions to match the overlay image
//             canvas.width = overlayImage.width;
//             canvas.height = overlayImage.height;

//             // Draw the overlay image on the canvas
//             ctx.drawImage(overlayImage, 0, 0);

//             // Set the font and color for the name and next of kin's phone number
//             ctx.font = 'bold 30px Arial';  // You can modify the font size and style
//             ctx.fillStyle = 'White';       // Text color (set to white)

//             // Set text alignment
//             ctx.textAlign = 'center'; // Center-align the text
//             const textX = canvas.width / 2 - 5; // Shifting the text 5px left from the center
//             const textY = (canvas.height - qrImage.height) / 3 + 45; // Position name above QR code (adjusted for lower position)
//             ctx.fillText(name, canvas.width / 2, textY); // Draw the name text

//             // Position next of kin phone number below the name (but still above the QR code)
//             const phoneTextY = textY + 40;  // You can adjust the gap here
//             ctx.fillText(nextOfKinPhone, canvas.width / 2, phoneTextY); // Draw the next of kin's phone number text

//             // Adjusted size for the QR code to fit the canvas
//             const qrCodeWidth = 280;  // QR code width increased by 50px (200px width)
//             const qrCodeHeight = 280; // QR code height doubled (300px height)
//             const qrX = (canvas.width - qrCodeWidth) / 2; // Center the QR code horizontally
//             const qrY = (canvas.height - qrCodeHeight) / 2 + 80; // Position QR code 50px lower on the canvas

//             // Draw the QR code with the desired size
//             ctx.drawImage(qrImage, qrX, qrY, qrCodeWidth, qrCodeHeight);

//             // Trigger the download immediately after generating the QR code
//             const qrImageUrl = canvas.toDataURL();

//             // Create a link element to trigger the download with a custom file name
//             const link = document.createElement('a');
//             // Use the patient's name and mobile for the filename
//             const fileName = `${name.replace(/\s+/g, '_')}_${mobile}.png`;
//             link.download = fileName;  // Set the download file name
//             link.href = qrImageUrl;
//             link.click(); // This will trigger the download
//         };
//     };
// }
// </script>

</body>
